feat: add precommit hook instructions
sparkbox/accessible-components pull request #33
Opened 2022-10-17 13:43 UTC by tisidro

FSA22V2-230

### Description:
Added pre-commit hook instructions to template.

### Spec:
Designs: [Designs](DESIGN_URL)

See Story: [FSA22V2-ISSUE](https://sparkbox.atlassian.net/browse/FSA22V2-ISSUE)

### Validation:

* [ ] This PR has code changes, and our linters still pass.
* [ ] This PR affects production code, so it was browser tested (see below).
* [ ] This PR has new code, so new tests were added or updated, and they pass.

#### To Validate:

1. Make sure all PR Checks have passed (GitHub Actions, CircleCI, Code Climate, etc).
2. Pull down all related branches.
3. In terminal: `npm run dev`.
4. Check [localhost:3000](http://localhost:3000/)for changes.
5. Run `npm run lint`.
6. Run axe Devtools on affected pages.
7. Confirm all tests pass.

Please check that pre-commit hook has been included in the instructions on the template.

#### Browser Testing

In these browsers, behavior & design closely match original specifications. A user is able to access all content and functionality, including the usability of required assistive devices, such as keyboard and screenreader.

**macOS**

* [ ] Safari (last 2 major versions)
* [ ] Chrome (last 6 months)
* [ ] Firefox (last 6 months)

**Windows**

* [ ] Chrome (last 6 months)
* [ ] Firefox (last 6 months)
* [ ] Edge (last 6 months)

**Mobile**

* [ ] Safari (last 2 major versions)
* [ ] Chrome on Android (last 6 months)
* [ ] Firefox on Android (last 6 months)

2022-10-17 14:02 UTC, empee3 commented on .github/pull_request_template.md
>  4. Check [localhost:3000](http://localhost:3000/)for changes.
This is a minor nitpick that I noticed on previous PRs, but could you add a space after `(http://localhost:3000/)`?

2022-10-17 16:02 UTC, dustin-jw requested changes

2022-10-17 21:35 UTC, dustin-jw approved these changes
This works for me, but we'll probably come back to this later to spruce up the documentation!

2022-10-17 21:35 UTC, dustin-jw commented on README.md
> +Run `npm run prepare` for husky pre-commit hook.
Hmm, looking at the README as a whole, we could do with rewriting it to reflect this project better. I won't let that block this, but I'll add a card at some point to update the whole README.

2022-10-19 18:16 UTC, empee3 submitted a review, later dismissed

2022-10-19 19:21 UTC, dustin-jw approved these changes

2022-10-19 19:22 UTC, merged