Related components section
sparkbox/accessible-components pull request #50
Opened 2022-10-25 18:33 UTC by bsmrdel101

### Description:

Each detail page should have a section that renders data from the “Related Components” field from Airtable. These will be links to other related components.

![Screen Shot 2022-10-25 at 1 28 37 PM](https://user-images.githubusercontent.com/43832671/197852926-1382a5fa-f4e0-4d6a-b842-b028e6f9d3b5.png)

### Spec:

Designs: [Figma](https://www.figma.com/file/UjMQEwUvAsnFAMhYNdUiVT/Apprenticeship-Capstone?node-id=84%3A663)

See Story: [FSA22V2-244](https://sparkbox.atlassian.net/jira/software/c/projects/FSA22V2/boards/125?modal=detail&selectedIssue=FSA22V2-244)

### Validation:

- [x] This PR has code changes, and our linters still pass.
- [x] This PR has new code, so new tests were added or updated, and they pass.

#### To Validate:

1. Make sure all PR Checks have passed (GitHub Actions, CircleCI, Code Climate, etc).
2. Pull down all related branches.
3. In terminal: `npm run dev`.
4. Run `npm run lint`.
5. Run axe Devtools on affected pages.
6. Confirm all tests pass.
7. Go to [localhost:3000](http://localhost:3000/accordian) and scroll down to this component. You should be able to click on any of the links there, and be taken to their relative details page.
8. Verify that the component is responsive to any screen size.

2022-10-25 21:20 UTC, tisidro requested changes
Hi Bennett, when I shrank it down it did this:
![image](https://user-images.githubusercontent.com/49820744/197884171-bcdb901c-f96b-4034-a573-27e0f3d06130.png)

I think it needs some responsiveness styling.

2022-10-26 14:33 UTC, tisidro submitted a review, later dismissed

2022-10-26 14:34 UTC, tisidro commented
Changes look great Bennet! :)

2022-10-26 17:49 UTC, changangus commented on src/styles/components/_related-components.scss
> +  padding: 6rem 8rem;
Saw a small issue in mobile that seems to be related to this padding here:
![Screen Shot 2022-10-26 at 1 44 40 PM](https://user-images.githubusercontent.com/63685366/198099137-393877b6-83a9-4f65-84fd-e4ece3564350.png)

Changed the values in the dev tools to test what would work, `2rem` was kind of just a random choice but it looks like the side padding should be smaller in mobile view:
![Screen Shot 2022-10-26 at 1 45 58 PM](https://user-images.githubusercontent.com/63685366/198099542-8f94006b-fd20-4cc4-bfca-e8d5f34b74c2.png)

2022-10-26 17:53 UTC, changangus commented on src/styles/components/_related-components.scss
> +$breakpoint-phone: 900px;
900px is a very large screen width to consider a mobile breakpoint, maybe include a tablet breakpoint and then also add a variable for the mobile breakpoint?

2022-10-26 18:00 UTC, changangus requested changes
Hey Bennett, logic looked great and everything was working really well, nice work! Just left a couple comments, both related to the mobile view styles of the `RelatedComponents` component.

2022-10-26 18:00 UTC, changangus commented on src/styles/components/_related-components.scss
> +  padding: 6rem 8rem;
Saw a small issue in mobile that seems to be related to this padding here:
![Screen Shot 2022-10-26 at 1 44 40 PM](https://user-images.githubusercontent.com/63685366/198099137-393877b6-83a9-4f65-84fd-e4ece3564350.png)

Changed the values in the dev tools to test what would work, `2rem` was kind of just a random choice but it looks like the side padding should be smaller in mobile view:
![Screen Shot 2022-10-26 at 1 45 58 PM](https://user-images.githubusercontent.com/63685366/198099542-8f94006b-fd20-4cc4-bfca-e8d5f34b74c2.png)

2022-10-26 18:00 UTC, changangus commented on src/components/RelatedComponents.jsx
> +          alt=""
empty alt for decorative image, nice!

2022-10-27 12:56 UTC, changangus approved these changes
Hey Bennett, it's looking good and working great! Nice job!

2022-10-27 13:56 UTC, merged